# Generated by Django 5.2.3 on 2025-06-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0002_pais_alter_estudiante_id_alter_numerotelefonico_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='num_habitantes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pais',
            name='num_provincias',
            field=models.IntegerField(),
        ),
    ]
